server:
  port: 9090
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/user_db
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialization-mode: always
    jpa:
      show-sql: true
    security:
      user:
        name: root
        password: root

